### ISSUE TITLE
could not eval camel-snake-kebab.core in self-hosted clojurescript.

### ISSUE THREAD

**Issue by guruma** [clj-commons/camel-snake-kebab#46]
[planck](https://github.com/mfikes/planck) and [lumo](https://github.com/anmonteiro/lumo) use the self-hosted clojurescript compiler.

When _required_ in planck or lumo, camel-snake-kebab.core namespace can't be loaded.

The following shows how I meet the case.

<img width="685" alt="2018-03-08 9 07 27" src="https://user-images.githubusercontent.com/534540/37150383-ddc533a8-2314-11e8-89cc-1b4532c64148.png">

**Comment by qerub** [comment]
I get another error with Planck (version 2.11.0):

```
% planck -c src -e "(require 'camel-snake-kebab.core)"
Could not eval camel-snake-kebab.internals.macros in file <…>/camel-snake-kebab/src/camel_snake_kebab/internals/macros.clj
Assert failed: Argument to resolve must be a quoted symbol
(core/and (seq? quoted-sym) (= (quote quote) (first quoted-sym))) at line 15 <…>/camel-snake-kebab/src/camel_snake_kebab/internals/macros.clj
```

I'm afraid I don't have the time to look into Planck compatibility but am happy to receive patches.
