### ISSUE TITLE
Conversion from bean function fails

### ISSUE THREAD

**Issue by brown131** [clj-commons/camel-snake-kebab#50]
Converting with transform-keys using the clojure.core.bean function gives the error:

UnsupportedOperationException empty  clojure.core.proxy$clojure.lang.APersistentMap$ff19274a.empty (:-1)

Here is an example:

$ clj -Sdeps "{:deps {camel-snake-kebab {:mvn/version \"0.4.0\"}}}"
Clojure 1.9.0
user=> (require ['camel-snake-kebab.core :refer :all])
nil
user=> (require ['camel-snake-kebab.extras :refer :all])
nil
(->> (java.util.Date.)
     (bean)
     (transform-keys ->kebab-case)
     :timezone-offset)
UnsupportedOperationException empty  clojure.core.proxy$clojure.lang.APersistentMap$ff19274a.empty (:-1)

 Interestingly, transform-keys works fine if I use a map directly, but not from the results the bean function:

user=> (bean (java.util.Date.))
{:day 5, :date 8, :time 1528508211784, :month 5, :seconds 51, :year 118, :class java.util.Date, :timezoneOffset 300, :hours 20, :minutes 36}
user=> (transform-keys ->kebab-case-keyword {:day 5, :date 8, :time 1528508211784, :month 5, :seconds 51, :year 118, :class java.util.Date, :timezoneOffset 300, :hours 20, :minutes 36})
{:day 5, :date 8, :time 1528508211784, :month 5, :timezone-offset 300, :seconds 51, :year 118, :class java.util.Date, :hours 20, :minutes 36}

**Comment by qerub** [comment]
The return value from `bean` has changed so it's no longer compatible with `postwalk` used inside `transform-keys`.
