### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by tobyclemson** [clj-commons/camel-snake-kebab#61]
Hi there,

I'm a Cursive user and it would be really great to get [commit 13dda807](https://github.com/clj-commons/camel-snake-kebab/commit/13dda80700a7eca83eaf2d48a4b628f4236454a2) into a release to prevent it complaining about undeclared symbols.

At the moment I'm using [lein-git-down](https://github.com/reifyhealth/lein-git-down) to fetch from github but this is non-ideal as it places requirements on consuming projects of any libraries.

Would it be possible to get a new release into maven or clojars?

Thanks,
Toby

**Comment by qerub** [comment]
Hi @tobyclemson!

Sure, here you go: https://clojars.org/camel-snake-kebab/versions/0.4.1

Let me know if there are any problems and sorry for the delay; I missed the issue notification. (While the issue backlog is embarrassingly long, easy issues like this should not be stalled.)

**Comment by tobyclemson** [comment]
@qerub That's great, thanks!
