### ISSUE TITLE
Request for a new version release

### ISSUE THREAD

**Issue by tlonist-sang** [clj-commons/camel-snake-kebab#80]
The previous update took place on Oct 19, 2020; and since then there were five PRs, the last of which is essential for my codebase. Can you release a new version containing the latest PR? It will be much appreciated. @qerub

**Comment by qerub** [comment]
Here you go: https://clojars.org/camel-snake-kebab/versions/0.4.3

> […] since then there were five PRs, the last of which is essential for my codebase.

The only functional change since 0.4.2 is https://github.com/clj-commons/camel-snake-kebab/pull/79 which changes `camel-snake-kebab.extras/transform-keys` to keep metadata.
